apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: rabbitmq-operator-logger-configuration
  labels:
    app.kubernetes.io/name: rabbitmq-operator-logger-configuration
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: helm
data:
  # Define additional logging configuration.
  custom-logger-levels.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Loggers>
        <Root level="{{ .Values.logging.level }}">
            <AppenderRef ref="Console"/>
        </Root>

        {{- range $name, $level := .Values.logging.additional }}
        <Logger name="{{ $name }}" level="{{ $level }}"/>
        {{- end }}
    </Loggers>
