apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: rabbitmq-startup-scripts
  labels:
    app.kubernetes.io/name: rabbitmq-startup-scripts
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: helm
data:
  # This ConfigMap defines a script that is run as the pod starts up.  It exists to create a
  # monitoring user (and any other users we may decide on in the future).  There aren't really
  # any other good options for getting additional users in - the environment variable route only
  # allows for a single user, and if we attempt to import a resources file any users defined
  # there take precedence over the environment variables.
  #
  # By default the monitoring role doesn't have access to any vhosts.  We use this user for
  # Datadog, which access the default vhost via "/api/aliveness-test/%2F".  To enable this to
  # work we need to explicitly grant permissions.  Per
  # https://lists.rabbitmq.com/pipermail/rabbitmq-discuss/2012-November/024132.html these are
  # the minimum necessary permissions.
  users.sh: |
    #!/usr/bin/env bash
    rabbitmqctl wait -t 60 "/var/lib/rabbitmq/mnesia/${RABBITMQ_NODENAME}.pid"
    rabbitmqctl add_user monitoring monitoring
    rabbitmqctl set_user_tags monitoring monitoring
    rabbitmqctl set_permissions -p / monitoring '^aliveness-test$' '^amq\.default$' '^aliveness-test$'
