apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rabbitmqnetworkpartitions.indeed.com
  labels:
    app.kubernetes.io/name: rabbitmqnetworkpartition-crd
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  group: indeed.com
  names:
    kind: RabbitMQNetworkPartitionCustomResource
    listKind: RabbitMQNetworkPartitionCustomResourceList
    plural: rabbitmqnetworkpartitions
    singular: rabbitmqnetworkpartition
    shortNames:
      - rmqnp
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
