apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rabbitmqs.indeed.com
  labels:
    app.kubernetes.io/name: rabbitmq-crd
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  group: indeed.com
  names:
    kind: RabbitMQCustomResource
    listKind: RabbitMQCustomResourceList
    plural: rabbitmqs
    singular: rabbitmq
    shortNames:
      - rmq
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            rabbitMQImage:
              type: string
            initContainerImage:
              type: string
            createLoadBalancer:
              type: boolean
            preserveOrphanPVCs:
              type: boolean
            replicas:
              type: number
              minimum: 0
            compute:
              properties:
                cpuRequest:
                  type: string
                memory:
                  type: string
            storage:
              properties:
                storageClassName:
                  type: string
                limit:
                  type: string
            clusterSpec:
              properties:
                highWatermarkFraction:
                  type: number
                  minimum: 0
                  maximum: 1.0
