apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: rabbitmq-operator
  labels:
    app.kubernetes.io/name: rabbitmq-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq-operator
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
        - image: {{ .Values.image.url }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: rabbitmq-operator
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: logging-configuration
              mountPath: /logging-configuration
      serviceAccountName: rabbitmq-operator
      volumes:
        - name: logging-configuration
          configMap:
            name: rabbitmq-operator-logger-configuration
