apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: rabbitmq-user
  labels:
    app.kubernetes.io/name: rabbitmq-user
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: helm
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
