apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: volume
  labels:
    app.kubernetes.io/name: volume
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: volume
  template:
    metadata:
      labels:
        app.kubernetes.io/name: volume
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        app.kubernetes.io/managed-by: helm
    spec:
      serviceAccountName: volume
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: data
          hostPath:
            path: /data/seaweedfs
            type: DirectoryOrCreate
      containers:
        - name: weed
          image: {{ .Values.volumeServer.image.repository }}:{{ .Values.volumeServer.image.tag }}
          imagePullPolicy: {{ .Values.volumeServer.image.pullPolicy }}
          env:
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - volume
            - -dir=/data/
            - -mserver={{ include "manager.servers" . }}
            - -ip=$(PODIP)
            - -port=8080
          ports:
            - containerPort: 18080
              name: grpc
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: data
              subPath: volume
              mountPath: /data/
              readOnly: false
          securityContext:
            runAsUser: 0
            runAsGroup: 0
