apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: filer
  labels:
    app.kubernetes.io/name: filer
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: filer
  ports:
    - port: 18888
      name: grpc
      protocol: TCP
    - port: 8888
      name: http
      protocol: TCP
