apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: s3
  labels:
    app.kubernetes.io/name: s3
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: s3
  ports:
    - port: 8333
      name: http
      protocol: TCP
{{- if .Values.s3Server.createLoadBalanacer }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: s3-lb
  labels:
    app.kubernetes.io/name: s3
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: s3
  ports:
    - port: 8333
      name: http
      protocol: TCP
{{- end }}
