---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "effx.fullname" . }}
  labels:
    {{- include "effx.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps", ""]
    resources: ["pods", "services", "replicationcontrollers", "deployments"]
    verbs: ["get", "watch", "list"]
