{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "effx.serviceAccountName" . }}
  labels:
    {{- include "effx.labels" . | nindent 4 }}
{{- end -}}
