name: seaweedfs

on:
  push:
    paths:
      - '.github/workflows/seaweedfs.yaml'
      - 'docker/seaweedfs/**'

jobs:
  build:
    env:
      VERSION: $(cat docker/seaweedfs/VERSION)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USERNAME}" --password-stdin
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        env:
          VERSION: ${{ env.VERSION }}
          IMAGE: mjpitz/seaweedfs
          IMAGE_PATH: docker/seaweedfs
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg=VERSION=${VERSION} \
            --tag ${IMAGE}:latest \
            --tag ${IMAGE}:${VERSION} \
            -f ${IMAGE_PATH}/Dockerfile \
            ${IMAGE_PATH} \
            --push
